import type { INodeProperties } from 'n8n-workflow';

export const defaultDescription: INodeProperties[] = [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					]
				}
			},
			"options": [
				{
					"name": "Apply Archive Rule",
					"value": "Apply Archive Rule",
					"action": "Apply Archive Rule",
					"description": "Retroactively applies the archive rule to existing findings that meet the archive rule criteria.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/archive-rule"
						}
					}
				},
				{
					"name": "Cancel Policy Generation",
					"value": "Cancel Policy Generation",
					"action": "Cancel Policy Generation",
					"description": "Cancels the requested policy generation.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/policy/generation/{{$parameter[\"jobId\"]}}"
						}
					}
				},
				{
					"name": "Get Generated Policy",
					"value": "Get Generated Policy",
					"action": "Get Generated Policy",
					"description": "Retrieves the policy that was generated using <code>StartPolicyGeneration</code>. ",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/policy/generation/{{$parameter[\"jobId\"]}}"
						}
					}
				},
				{
					"name": "Create Access Preview",
					"value": "Create Access Preview",
					"action": "Create Access Preview",
					"description": "Creates an access preview that allows you to preview IAM Access Analyzer findings for your resource before deploying resource permissions.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/access-preview"
						}
					}
				},
				{
					"name": "Create Analyzer",
					"value": "Create Analyzer",
					"action": "Create Analyzer",
					"description": "Creates an analyzer for your account.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/analyzer"
						}
					}
				},
				{
					"name": "List Analyzers",
					"value": "List Analyzers",
					"action": "List Analyzers",
					"description": "Retrieves a list of analyzers.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/analyzer"
						}
					}
				},
				{
					"name": "Create Archive Rule",
					"value": "Create Archive Rule",
					"action": "Create Archive Rule",
					"description": "<p>Creates an archive rule for the specified analyzer. Archive rules automatically archive new findings that meet the criteria you define when you create the rule.</p> <p>To learn about filter keys that you can use to create an archive rule, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-filter-keys.html\">IAM Access Analyzer filter keys</a> in the <b>IAM User Guide</b>.</p>",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}/archive-rule"
						}
					}
				},
				{
					"name": "List Archive Rules",
					"value": "List Archive Rules",
					"action": "List Archive Rules",
					"description": "Retrieves a list of archive rules created for the specified analyzer.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}/archive-rule"
						}
					}
				},
				{
					"name": "Delete Analyzer",
					"value": "Delete Analyzer",
					"action": "Delete Analyzer",
					"description": "Deletes the specified analyzer. When you delete an analyzer, IAM Access Analyzer is disabled for the account or organization in the current or specific Region. All findings that were generated by the analyzer are deleted. You cannot undo this action.",
					"routing": {
						"request": {
							"method": "DELETE",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}"
						}
					}
				},
				{
					"name": "Get Analyzer",
					"value": "Get Analyzer",
					"action": "Get Analyzer",
					"description": "Retrieves information about the specified analyzer.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}"
						}
					}
				},
				{
					"name": "Delete Archive Rule",
					"value": "Delete Archive Rule",
					"action": "Delete Archive Rule",
					"description": "Deletes the specified archive rule.",
					"routing": {
						"request": {
							"method": "DELETE",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}/archive-rule/{{$parameter[\"ruleName\"]}}"
						}
					}
				},
				{
					"name": "Get Archive Rule",
					"value": "Get Archive Rule",
					"action": "Get Archive Rule",
					"description": "<p>Retrieves information about an archive rule.</p> <p>To learn about filter keys that you can use to create an archive rule, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-filter-keys.html\">IAM Access Analyzer filter keys</a> in the <b>IAM User Guide</b>.</p>",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}/archive-rule/{{$parameter[\"ruleName\"]}}"
						}
					}
				},
				{
					"name": "Update Archive Rule",
					"value": "Update Archive Rule",
					"action": "Update Archive Rule",
					"description": "Updates the criteria and values for the specified archive rule.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/analyzer/{{$parameter[\"analyzerName\"]}}/archive-rule/{{$parameter[\"ruleName\"]}}"
						}
					}
				},
				{
					"name": "Get Access Preview",
					"value": "Get Access Preview",
					"action": "Get Access Preview",
					"description": "Retrieves information about an access preview for the specified analyzer.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/access-preview/{{$parameter[\"accessPreviewId\"]}}#analyzerArn"
						}
					}
				},
				{
					"name": "Get Analyzed Resource",
					"value": "Get Analyzed Resource",
					"action": "Get Analyzed Resource",
					"description": "Retrieves information about a resource that was analyzed.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/analyzed-resource#analyzerArn&resourceArn"
						}
					}
				},
				{
					"name": "Get Finding",
					"value": "Get Finding",
					"action": "Get Finding",
					"description": "Retrieves information about the specified finding.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/finding/{{$parameter[\"id\"]}}#analyzerArn"
						}
					}
				},
				{
					"name": "List Access Preview Findings",
					"value": "List Access Preview Findings",
					"action": "List Access Preview Findings",
					"description": "Retrieves a list of access preview findings generated by the specified access preview.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/access-preview/{{$parameter[\"accessPreviewId\"]}}"
						}
					}
				},
				{
					"name": "List Access Previews",
					"value": "List Access Previews",
					"action": "List Access Previews",
					"description": "Retrieves a list of access previews for the specified analyzer.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/access-preview#analyzerArn"
						}
					}
				},
				{
					"name": "List Analyzed Resources",
					"value": "List Analyzed Resources",
					"action": "List Analyzed Resources",
					"description": "Retrieves a list of resources of the specified type that have been analyzed by the specified analyzer..",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/analyzed-resource"
						}
					}
				},
				{
					"name": "List Findings",
					"value": "List Findings",
					"action": "List Findings",
					"description": "<p>Retrieves a list of findings generated by the specified analyzer.</p> <p>To learn about filter keys that you can use to retrieve a list of findings, see <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-filter-keys.html\">IAM Access Analyzer filter keys</a> in the <b>IAM User Guide</b>.</p>",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/finding"
						}
					}
				},
				{
					"name": "Update Findings",
					"value": "Update Findings",
					"action": "Update Findings",
					"description": "Updates the status for the specified findings.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/finding"
						}
					}
				},
				{
					"name": "List Policy Generations",
					"value": "List Policy Generations",
					"action": "List Policy Generations",
					"description": "Lists all of the policy generations requested in the last seven days.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/policy/generation"
						}
					}
				},
				{
					"name": "Start Policy Generation",
					"value": "Start Policy Generation",
					"action": "Start Policy Generation",
					"description": "Starts the policy generation request.",
					"routing": {
						"request": {
							"method": "PUT",
							"url": "=/policy/generation"
						}
					}
				},
				{
					"name": "List Tags For Resource",
					"value": "List Tags For Resource",
					"action": "List Tags For Resource",
					"description": "Retrieves a list of tags applied to the specified resource.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/tags/{{$parameter[\"resourceArn\"]}}"
						}
					}
				},
				{
					"name": "Tag Resource",
					"value": "Tag Resource",
					"action": "Tag Resource",
					"description": "Adds a tag to the specified resource.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/tags/{{$parameter[\"resourceArn\"]}}"
						}
					}
				},
				{
					"name": "Start Resource Scan",
					"value": "Start Resource Scan",
					"action": "Start Resource Scan",
					"description": "Immediately starts a scan of the policies applied to the specified resource.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/resource/scan"
						}
					}
				},
				{
					"name": "Untag Resource",
					"value": "Untag Resource",
					"action": "Untag Resource",
					"description": "Removes a tag from the specified resource.",
					"routing": {
						"request": {
							"method": "DELETE",
							"url": "=/tags/{{$parameter[\"resourceArn\"]}}#tagKeys"
						}
					}
				},
				{
					"name": "Validate Policy",
					"value": "Validate Policy",
					"action": "Validate Policy",
					"description": "Requests the validation of a policy and returns a list of findings. The findings help you identify issues and provide actionable recommendations to resolve the issue and enable you to author functional policies that meet security best practices. ",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/policy/validation"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "PUT /archive-rule",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Apply Archive Rule"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The Amazon resource name (ARN) of the analyzer.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Apply Archive Rule"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Rule Name",
			"name": "ruleName",
			"type": "string",
			"default": "",
			"description": "The name of the rule to apply.",
			"routing": {
				"send": {
					"property": "ruleName",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Apply Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "A client token.",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Apply Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Apply Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "PUT /policy/generation/{jobId}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Cancel Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "Job Id",
			"name": "jobId",
			"required": true,
			"description": "The <code>JobId</code> that is returned by the <code>StartPolicyGeneration</code> operation. The <code>JobId</code> can be used with <code>GetGeneratedPolicy</code> to retrieve the generated policies or used with <code>CancelPolicyGeneration</code> to cancel the policy generation request.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Cancel Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Cancel Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "GET /policy/generation/{jobId}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Generated Policy"
					]
				}
			}
		},
		{
			"displayName": "Job Id",
			"name": "jobId",
			"required": true,
			"description": "The <code>JobId</code> that is returned by the <code>StartPolicyGeneration</code> operation. The <code>JobId</code> can be used with <code>GetGeneratedPolicy</code> to retrieve the generated policies or used with <code>CancelPolicyGeneration</code> to cancel the policy generation request.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Generated Policy"
					]
				}
			}
		},
		{
			"displayName": "Include Resource Placeholders",
			"name": "includeResourcePlaceholders",
			"description": "<p>The level of detail that you want to generate. You can specify whether to generate policies with placeholders for resource ARNs for actions that support resource level granularity in policies.</p> <p>For example, in the resource section of a policy, you can receive a placeholder such as <code>\"Resource\":\"arn:aws:s3:::${BucketName}\"</code> instead of <code>\"*\"</code>.</p>",
			"default": true,
			"type": "boolean",
			"routing": {
				"send": {
					"type": "query",
					"property": "includeResourcePlaceholders",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Generated Policy"
					]
				}
			}
		},
		{
			"displayName": "Include Service Level Template",
			"name": "includeServiceLevelTemplate",
			"description": "<p>The level of detail that you want to generate. You can specify whether to generate service-level policies. </p> <p>IAM Access Analyzer uses <code>iam:servicelastaccessed</code> to identify services that have been used recently to create this service-level template.</p>",
			"default": true,
			"type": "boolean",
			"routing": {
				"send": {
					"type": "query",
					"property": "includeServiceLevelTemplate",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Generated Policy"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Generated Policy"
					]
				}
			}
		},
		{
			"displayName": "PUT /access-preview",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Access Preview"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the account analyzer</a> used to generate the access preview. You can only create an access preview for analyzers with an <code>Account</code> type and <code>Active</code> status.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Access Preview"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Configurations",
			"name": "configurations",
			"type": "json",
			"default": "{}",
			"description": "Access control configuration for your resource that is used to generate the access preview. The access preview includes findings for external access allowed to the resource with the proposed access control configuration. The configuration must contain exactly one element.",
			"routing": {
				"send": {
					"property": "configurations",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Access Preview"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "A client token.",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Access Preview"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Access Preview"
					]
				}
			}
		},
		{
			"displayName": "PUT /analyzer",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"type": "string",
			"default": "",
			"description": "The name of the analyzer to create.",
			"routing": {
				"send": {
					"property": "analyzerName",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Type",
			"name": "type",
			"type": "options",
			"default": "ACCOUNT",
			"description": "The type of analyzer to create. Only ACCOUNT and ORGANIZATION analyzers are supported. You can create only one analyzer per account per Region. You can create up to 5 analyzers per organization per Region.",
			"options": [
				{
					"name": "ACCOUNT",
					"value": "ACCOUNT"
				},
				{
					"name": "ORGANIZATION",
					"value": "ORGANIZATION"
				}
			],
			"routing": {
				"send": {
					"property": "type",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Archive Rules",
			"name": "archiveRules",
			"type": "json",
			"default": "[\n  {\n    \"filter\": {}\n  }\n]",
			"description": "Specifies the archive rules to add for the analyzer. Archive rules automatically archive findings that meet the criteria you define for the rule.",
			"routing": {
				"send": {
					"property": "archiveRules",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Tags",
			"name": "tags",
			"type": "json",
			"default": "{}",
			"description": "The tags to apply to the analyzer.",
			"routing": {
				"send": {
					"property": "tags",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "A client token.",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Analyzer"
					]
				}
			}
		},
		{
			"displayName": "GET /analyzer",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzers"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "A token used for pagination of results returned.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzers"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "The maximum number of results to return in the response.",
			"default": 0,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzers"
					]
				}
			}
		},
		{
			"displayName": "Type",
			"name": "type",
			"description": "The type of analyzer.",
			"default": "ACCOUNT",
			"type": "options",
			"options": [
				{
					"name": "ACCOUNT",
					"value": "ACCOUNT"
				},
				{
					"name": "ORGANIZATION",
					"value": "ORGANIZATION"
				}
			],
			"routing": {
				"send": {
					"type": "query",
					"property": "type",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzers"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzers"
					]
				}
			}
		},
		{
			"displayName": "PUT /analyzer/{analyzerName}/archive-rule",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the created analyzer.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Archive Rule"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Rule Name",
			"name": "ruleName",
			"type": "string",
			"default": "",
			"description": "The name of the rule to create.",
			"routing": {
				"send": {
					"property": "ruleName",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Archive Rule"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Filter",
			"name": "filter",
			"type": "json",
			"default": "{}",
			"description": "The criteria for the rule.",
			"routing": {
				"send": {
					"property": "filter",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "A client token.",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Create Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "GET /analyzer/{analyzerName}/archive-rule",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Archive Rules"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the analyzer to retrieve rules from.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Archive Rules"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "A token used for pagination of results returned.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Archive Rules"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "The maximum number of results to return in the request.",
			"default": 0,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Archive Rules"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Archive Rules"
					]
				}
			}
		},
		{
			"displayName": "DELETE /analyzer/{analyzerName}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the analyzer to delete.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"description": "A client token.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "clientToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Analyzer"
					]
				}
			}
		},
		{
			"displayName": "GET /analyzer/{analyzerName}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the analyzer retrieved.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzer"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzer"
					]
				}
			}
		},
		{
			"displayName": "DELETE /analyzer/{analyzerName}/archive-rule/{ruleName}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the analyzer that associated with the archive rule to delete.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Rule Name",
			"name": "ruleName",
			"required": true,
			"description": "The name of the rule to delete.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"description": "A client token.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "clientToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Delete Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "GET /analyzer/{analyzerName}/archive-rule/{ruleName}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the analyzer to retrieve rules from.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Rule Name",
			"name": "ruleName",
			"required": true,
			"description": "The name of the rule to retrieve.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "PUT /analyzer/{analyzerName}/archive-rule/{ruleName}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Name",
			"name": "analyzerName",
			"required": true,
			"description": "The name of the analyzer to update the archive rules for.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Rule Name",
			"name": "ruleName",
			"required": true,
			"description": "The name of the rule to update.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Archive Rule"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Filter",
			"name": "filter",
			"type": "json",
			"default": "{}",
			"description": "A filter to match for the rules to update. Only rules that match the filter are updated.",
			"routing": {
				"send": {
					"property": "filter",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "A client token.",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Archive Rule"
					]
				}
			}
		},
		{
			"displayName": "GET /access-preview/{accessPreviewId}#analyzerArn",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Access Preview"
					]
				}
			}
		},
		{
			"displayName": "Access Preview Id",
			"name": "accessPreviewId",
			"required": true,
			"description": "The unique ID for the access preview.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Access Preview"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"required": true,
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> used to generate the access preview.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "analyzerArn",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Access Preview"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Access Preview"
					]
				}
			}
		},
		{
			"displayName": "GET /analyzed-resource#analyzerArn&resourceArn",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzed Resource"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"required": true,
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> to retrieve information from.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "analyzerArn",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzed Resource"
					]
				}
			}
		},
		{
			"displayName": "Resource Arn",
			"name": "resourceArn",
			"required": true,
			"description": "The ARN of the resource to retrieve information about.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "resourceArn",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzed Resource"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Analyzed Resource"
					]
				}
			}
		},
		{
			"displayName": "GET /finding/{id}#analyzerArn",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Finding"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"required": true,
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> that generated the finding.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "analyzerArn",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Finding"
					]
				}
			}
		},
		{
			"displayName": "Id",
			"name": "id",
			"required": true,
			"description": "The ID of the finding to retrieve.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Finding"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Get Finding"
					]
				}
			}
		},
		{
			"displayName": "POST /access-preview/{accessPreviewId}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Access Preview Id",
			"name": "accessPreviewId",
			"required": true,
			"description": "The unique ID for the access preview.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "Pagination limit",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "Pagination token",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> used to generate the access.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Filter",
			"name": "filter",
			"type": "json",
			"default": "{}",
			"description": "Criteria to filter the returned findings.",
			"routing": {
				"send": {
					"property": "filter",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"type": "string",
			"default": "",
			"description": "A token used for pagination of results returned.",
			"routing": {
				"send": {
					"property": "nextToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"type": "number",
			"default": 0,
			"description": "The maximum number of results to return in the response.",
			"routing": {
				"send": {
					"property": "maxResults",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Preview Findings"
					]
				}
			}
		},
		{
			"displayName": "GET /access-preview#analyzerArn",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Previews"
					]
				}
			}
		},
		{
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"required": true,
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> used to generate the access preview.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "analyzerArn",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Previews"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "A token used for pagination of results returned.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Previews"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "The maximum number of results to return in the response.",
			"default": 0,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Previews"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Access Previews"
					]
				}
			}
		},
		{
			"displayName": "POST /analyzed-resource",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "Pagination limit",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "Pagination token",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> to retrieve a list of analyzed resources from.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "Resource Type",
			"name": "resourceType",
			"type": "options",
			"default": "AWS::S3::Bucket",
			"description": "The type of resource.",
			"options": [
				{
					"name": "AWS S 3 Bucket",
					"value": "AWS::S3::Bucket"
				},
				{
					"name": "AWS IAM Role",
					"value": "AWS::IAM::Role"
				},
				{
					"name": "AWS SQS Queue",
					"value": "AWS::SQS::Queue"
				},
				{
					"name": "AWS Lambda Function",
					"value": "AWS::Lambda::Function"
				},
				{
					"name": "AWS Lambda Layer Version",
					"value": "AWS::Lambda::LayerVersion"
				},
				{
					"name": "AWS KMS Key",
					"value": "AWS::KMS::Key"
				},
				{
					"name": "AWS Secrets Manager Secret",
					"value": "AWS::SecretsManager::Secret"
				},
				{
					"name": "AWS EFS File System",
					"value": "AWS::EFS::FileSystem"
				},
				{
					"name": "AWS EC 2 Snapshot",
					"value": "AWS::EC2::Snapshot"
				},
				{
					"name": "AWS ECR Repository",
					"value": "AWS::ECR::Repository"
				},
				{
					"name": "AWS RDS DB Snapshot",
					"value": "AWS::RDS::DBSnapshot"
				},
				{
					"name": "AWS RDS DB Cluster Snapshot",
					"value": "AWS::RDS::DBClusterSnapshot"
				},
				{
					"name": "AWS SNS Topic",
					"value": "AWS::SNS::Topic"
				}
			],
			"routing": {
				"send": {
					"property": "resourceType",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"type": "string",
			"default": "",
			"description": "A token used for pagination of results returned.",
			"routing": {
				"send": {
					"property": "nextToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"type": "number",
			"default": 0,
			"description": "The maximum number of results to return in the response.",
			"routing": {
				"send": {
					"property": "maxResults",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Analyzed Resources"
					]
				}
			}
		},
		{
			"displayName": "POST /finding",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "Pagination limit",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "Pagination token",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> to retrieve findings from.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Filter",
			"name": "filter",
			"type": "json",
			"default": "{}",
			"description": "A filter to match for the findings to return.",
			"routing": {
				"send": {
					"property": "filter",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Sort",
			"name": "sort",
			"type": "json",
			"default": "{\n  \"orderBy\": {}\n}",
			"description": "The criteria used to sort.",
			"routing": {
				"send": {
					"property": "sort",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"type": "string",
			"default": "",
			"description": "A token used for pagination of results returned.",
			"routing": {
				"send": {
					"property": "nextToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"type": "number",
			"default": 0,
			"description": "The maximum number of results to return in the response.",
			"routing": {
				"send": {
					"property": "maxResults",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Findings"
					]
				}
			}
		},
		{
			"displayName": "PUT /finding",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> that generated the findings to update.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Status",
			"name": "status",
			"type": "options",
			"default": "ACTIVE",
			"description": "The state represents the action to take to update the finding Status. Use <code>ARCHIVE</code> to change an Active finding to an Archived finding. Use <code>ACTIVE</code> to change an Archived finding to an Active finding.",
			"options": [
				{
					"name": "ACTIVE",
					"value": "ACTIVE"
				},
				{
					"name": "ARCHIVED",
					"value": "ARCHIVED"
				}
			],
			"routing": {
				"send": {
					"property": "status",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"displayName": "Ids",
			"name": "ids",
			"type": "json",
			"default": "[\n  null\n]",
			"description": "The IDs of the findings to update.",
			"routing": {
				"send": {
					"property": "ids",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"displayName": "Resource Arn",
			"name": "resourceArn",
			"type": "string",
			"default": "",
			"description": "The ARN of the resource identified in the finding.",
			"routing": {
				"send": {
					"property": "resourceArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "A client token.",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Update Findings"
					]
				}
			}
		},
		{
			"displayName": "GET /policy/generation",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Policy Generations"
					]
				}
			}
		},
		{
			"displayName": "Principal Arn",
			"name": "principalArn",
			"description": "The ARN of the IAM entity (user or role) for which you are generating a policy. Use this with <code>ListGeneratedPolicies</code> to filter the results to only include results for a specific principal.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "principalArn",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Policy Generations"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "The maximum number of results to return in the response.",
			"default": 0,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Policy Generations"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "A token used for pagination of results returned.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Policy Generations"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Policy Generations"
					]
				}
			}
		},
		{
			"displayName": "PUT /policy/generation",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Policy Generation"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Policy Generation Details",
			"name": "policyGenerationDetails",
			"type": "json",
			"default": "{}",
			"description": "Contains the ARN details about the IAM entity for which the policy is generated.",
			"routing": {
				"send": {
					"property": "policyGenerationDetails",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "Cloud Trail Details",
			"name": "cloudTrailDetails",
			"type": "json",
			"default": "{\n  \"trails\": [\n    {\n      \"cloudTrailArn\": {},\n      \"regions\": {},\n      \"allRegions\": {}\n    }\n  ],\n  \"accessRole\": {},\n  \"startTime\": {},\n  \"endTime\": {}\n}",
			"description": "Contains information about CloudTrail access.",
			"routing": {
				"send": {
					"property": "cloudTrailDetails",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "Client Token",
			"name": "clientToken",
			"type": "string",
			"default": "",
			"description": "<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, the subsequent retries with the same client token return the result from the original successful request and they have no additional effect.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>",
			"routing": {
				"send": {
					"property": "clientToken",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Policy Generation"
					]
				}
			}
		},
		{
			"displayName": "GET /tags/{resourceArn}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Tags For Resource"
					]
				}
			}
		},
		{
			"displayName": "Resource Arn",
			"name": "resourceArn",
			"required": true,
			"description": "The ARN of the resource to retrieve tags from.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Tags For Resource"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"List Tags For Resource"
					]
				}
			}
		},
		{
			"displayName": "POST /tags/{resourceArn}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Tag Resource"
					]
				}
			}
		},
		{
			"displayName": "Resource Arn",
			"name": "resourceArn",
			"required": true,
			"description": "The ARN of the resource to add the tag to.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Tag Resource"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Tags",
			"name": "tags",
			"type": "json",
			"default": "{}",
			"description": "The tags to add to the resource.",
			"routing": {
				"send": {
					"property": "tags",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Tag Resource"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Tag Resource"
					]
				}
			}
		},
		{
			"displayName": "POST /resource/scan",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Resource Scan"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Analyzer Arn",
			"name": "analyzerArn",
			"type": "string",
			"default": "",
			"description": "The <a href=\"https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-getting-started.html#permission-resources\">ARN of the analyzer</a> to use to scan the policies applied to the specified resource.",
			"routing": {
				"send": {
					"property": "analyzerArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Resource Scan"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Resource Arn",
			"name": "resourceArn",
			"type": "string",
			"default": "",
			"description": "The ARN of the resource to scan.",
			"routing": {
				"send": {
					"property": "resourceArn",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Resource Scan"
					]
				}
			}
		},
		{
			"displayName": "Resource Owner Account",
			"name": "resourceOwnerAccount",
			"type": "string",
			"default": "",
			"description": "The Amazon Web Services account ID that owns the resource. For most Amazon Web Services resources, the owning account is the account in which the resource was created.",
			"routing": {
				"send": {
					"property": "resourceOwnerAccount",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Resource Scan"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Start Resource Scan"
					]
				}
			}
		},
		{
			"displayName": "DELETE /tags/{resourceArn}#tagKeys",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Untag Resource"
					]
				}
			}
		},
		{
			"displayName": "Resource Arn",
			"name": "resourceArn",
			"required": true,
			"description": "The ARN of the resource to remove the tag from.",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Untag Resource"
					]
				}
			}
		},
		{
			"displayName": "Tag Keys",
			"name": "tagKeys",
			"required": true,
			"description": "The key for the tag to add.",
			"default": "[\n  null\n]",
			"type": "json",
			"routing": {
				"send": {
					"type": "query",
					"property": "tagKeys",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Untag Resource"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Untag Resource"
					]
				}
			}
		},
		{
			"displayName": "POST /policy/validation",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"displayName": "Max Results",
			"name": "maxResults",
			"description": "The maximum number of results to return in the response.",
			"default": 0,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "maxResults",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"displayName": "Next Token",
			"name": "nextToken",
			"description": "A token used for pagination of results returned.",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "nextToken",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"displayName": "Locale",
			"name": "locale",
			"type": "options",
			"default": "DE",
			"description": "The locale to use for localizing the findings.",
			"options": [
				{
					"name": "DE",
					"value": "DE"
				},
				{
					"name": "EN",
					"value": "EN"
				},
				{
					"name": "ES",
					"value": "ES"
				},
				{
					"name": "FR",
					"value": "FR"
				},
				{
					"name": "IT",
					"value": "IT"
				},
				{
					"name": "JA",
					"value": "JA"
				},
				{
					"name": "KO",
					"value": "KO"
				},
				{
					"name": "PT BR",
					"value": "PT_BR"
				},
				{
					"name": "ZH CN",
					"value": "ZH_CN"
				},
				{
					"name": "ZH TW",
					"value": "ZH_TW"
				}
			],
			"routing": {
				"send": {
					"property": "locale",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Policy Document",
			"name": "policyDocument",
			"type": "string",
			"default": "",
			"description": "The JSON policy document to use as the content for the policy.",
			"routing": {
				"send": {
					"property": "policyDocument",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Policy Type",
			"name": "policyType",
			"type": "options",
			"default": "IDENTITY_POLICY",
			"description": "<p>The type of policy to validate. Identity policies grant permissions to IAM principals. Identity policies include managed and inline policies for IAM roles, users, and groups. They also include service-control policies (SCPs) that are attached to an Amazon Web Services organization, organizational unit (OU), or an account.</p> <p>Resource policies grant permissions on Amazon Web Services resources. Resource policies include trust policies for IAM roles and bucket policies for Amazon S3 buckets. You can provide a generic input such as identity policy or resource policy or a specific input such as managed policy or Amazon S3 bucket policy. </p>",
			"options": [
				{
					"name": "IDENTITY POLICY",
					"value": "IDENTITY_POLICY"
				},
				{
					"name": "RESOURCE POLICY",
					"value": "RESOURCE_POLICY"
				},
				{
					"name": "SERVICE CONTROL POLICY",
					"value": "SERVICE_CONTROL_POLICY"
				}
			],
			"routing": {
				"send": {
					"property": "policyType",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"displayName": "Validate Policy Resource Type",
			"name": "validatePolicyResourceType",
			"type": "options",
			"default": "AWS::S3::Bucket",
			"description": "<p>The type of resource to attach to your resource policy. Specify a value for the policy validation resource type only if the policy type is <code>RESOURCE_POLICY</code>. For example, to validate a resource policy to attach to an Amazon S3 bucket, you can choose <code>AWS::S3::Bucket</code> for the policy validation resource type.</p> <p>For resource types not supported as valid values, IAM Access Analyzer runs policy checks that apply to all resource policies. For example, to validate a resource policy to attach to a KMS key, do not specify a value for the policy validation resource type and IAM Access Analyzer will run policy checks that apply to all resource policies.</p>",
			"options": [
				{
					"name": "AWS S 3 Bucket",
					"value": "AWS::S3::Bucket"
				},
				{
					"name": "AWS S 3 Access Point",
					"value": "AWS::S3::AccessPoint"
				},
				{
					"name": "AWS S 3 Multi Region Access Point",
					"value": "AWS::S3::MultiRegionAccessPoint"
				},
				{
					"name": "AWS S 3 Object Lambda Access Point",
					"value": "AWS::S3ObjectLambda::AccessPoint"
				},
				{
					"name": "AWS IAM Assume Role Policy Document",
					"value": "AWS::IAM::AssumeRolePolicyDocument"
				}
			],
			"routing": {
				"send": {
					"property": "validatePolicyResourceType",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
		{
			"displayName": "Hmac API Key",
			"name": "security_hmac",
			"type": "string",
			"default": "",
			"description": "Amazon Signature authorization v4",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Default"
					],
					"operation": [
						"Validate Policy"
					]
				}
			}
		},
];
